spring:
  application.name: spring-ai-accelerator [Your app name here!]
  profiles:
    group:
      rag:
        - jdbc
      history:
        - jdbc
      auth-azure:
        - jdbc
  flyway:
    enabled: false
    baseline-on-migrate: true
