spring:
  application.name: spring-ai-accelerator [Your app name here!]
  profiles:
    group:
      rag:
        - jdbc
      history:
        - jdbc
      auth-azure:
        - jdbc
      auth-aws:
        - jdbc
      secure-rag:
        - rag
  ai:
    openai:
      api-key: overwritten-by-env-var-if-open-ai-profile-is-active
    chat:
      observations:
        log-prompt: true
  flyway:
    enabled: false
    baseline-on-migrate: true

management:
  metrics:
    tags:
      application: spring-ai-accelerator
      # useful tags can be the application environment for example
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, env
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
