spring:
  application.name: spring-ai-accelerator [Your app name here!]
  profiles:
    group:
      rag:
        - jdbc
      history:
        - jdbc
      auth-azure:
        - jdbc
      auth-aws:
        - jdbc
      secure-rag:
        - rag
  ai:
    openai:
      api-key: overwritten-by-env-var-if-open-ai-profile-is-active
  flyway:
    enabled: false
    baseline-on-migrate: true
