-- FOR SESSION RELATED PROFILES
CREATE TABLE session
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id VARCHAR,
    chat_id VARCHAR,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

-- FOR SECURE RAG PROFILE
CREATE TABLE user_permission
(
    id             SERIAL,
    email          VARCHAR(255) NOT NULL,
    security_level VARCHAR(50)  NOT NULL
);

CREATE INDEX idx_user_permission_email ON user_permission (email);

INSERT INTO user_permission (email, security_level)
VALUES ('christianmartin@zerofifty-it.nl', 'CONFIDENTIAL'),
       ('someone.awesome@company.com', 'PUBLIC');

-- If not auto-created
CREATE TABLE IF NOT EXISTS vector_store (
     id UUID PRIMARY KEY,
     content TEXT,
     metadata JSONB,
     embedding VECTOR(1024)
);

-- Index on metadata for fast filtering
CREATE INDEX idx_vector_metadata ON vector_store USING GIN (metadata);
